" my vim config

set history=700
set autoread
set so=7
set ruler
set cmdheight=2
set backspace=eol,start,indent
set ignorecase
set smartcase
set hlsearch
set incsearch
set showmatch
set mat=2
set noerrorbells
set novisualbell
set t_vb=
set tm=500
syntax on
set nobackup
set nowb
set noswapfile
set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set ai "Auto indent
set si "Smart indent
set wrap "Wrap lines
set shell=/bin/bash

call plug#begin('~/.vim/plugged')
Plug 'fatih/vim-go'
Plug 'jiangmiao/auto-pairs'
call plug#end()

